// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type QuickReply struct {
	ID          int64          `json:"id"`
	ScriptCode  sql.NullString `json:"script_code"`
	ContentType sql.NullString `json:"content_type"`
	Title       sql.NullString `json:"title"`
	Payload     sql.NullString `json:"payload"`
	ImageUrl    sql.NullString `json:"image_url"`
	Status      int32          `json:"status"`
	OrderNumber sql.NullInt32  `json:"order_number"`
}

type Script struct {
	Code            string         `json:"code"`
	ActionProcessor sql.NullString `json:"action_processor"`
	ActionRetriever sql.NullString `json:"action_retriever"`
	MessageFailed   sql.NullString `json:"message_failed"`
	MessageImage    sql.NullString `json:"message_image"`
	MessageSucceed  sql.NullString `json:"message_succeed"`
	MessageText     sql.NullString `json:"message_text"`
	OrderNumber     sql.NullInt32  `json:"order_number"`
	ParentCode      sql.NullString `json:"parent_code"`
}

type User struct {
	ID        string         `json:"id"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
	Status    int32          `json:"status"`
	FullName  sql.NullString `json:"full_name"`
	IsMentor  sql.NullString `json:"is_mentor"`
	UserName  sql.NullString `json:"user_name"`
}
