// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	MentorID  string    `json:"mentor_id"`
	ValidTime time.Time `json:"valid_time"`
	Status    int32     `json:"status"`
}

type Question struct {
	ID            int64  `json:"id"`
	TopicCode     string `json:"topic_code"`
	ContentText   string `json:"content_text"`
	ContentImage  string `json:"content_image"`
	CorrectAnswer string `json:"correct_answer"`
	// 1 - de
	// 2 - trung binh
	// 3 - kho
	// 4 - rat kho
	Difficult   int32  `json:"difficult"`
	SubjectCode string `json:"subject_code"`
	Status      int32  `json:"status"`
}

type QuickReply struct {
	ID          int64          `json:"id"`
	ScriptCode  string         `json:"script_code"`
	ContentType string         `json:"content_type"`
	Title       string         `json:"title"`
	Payload     string         `json:"payload"`
	ImageUrl    sql.NullString `json:"image_url"`
	Status      int32          `json:"status"`
	OrderNumber sql.NullInt32  `json:"order_number"`
}

type Script struct {
	Code            string         `json:"code"`
	ActionProcessor string         `json:"action_processor"`
	MessageFailed   sql.NullString `json:"message_failed"`
	MessageImage    sql.NullString `json:"message_image"`
	MessageSucceed  sql.NullString `json:"message_succeed"`
	MessageText     sql.NullString `json:"message_text"`
	OrderNumber     sql.NullInt32  `json:"order_number"`
	ParentCode      sql.NullString `json:"parent_code"`
}

type SessionContext struct {
	ID         sql.NullInt64 `json:"id"`
	UserID     string        `json:"user_id"`
	ScriptCode string        `json:"script_code"`
	ValidTime  time.Time     `json:"valid_time"`
}

type Subject struct {
	SubjectCode string         `json:"subject_code"`
	SubjectName string         `json:"subject_name"`
	Status      int32          `json:"status"`
	OrderNumber int32          `json:"order_number"`
	Image       sql.NullString `json:"image"`
}

type Topic struct {
	TopicName    sql.NullString `json:"topic_name"`
	Description  sql.NullString `json:"description"`
	DocumentLink sql.NullString `json:"document_link"`
	SubjectCode  string         `json:"subject_code"`
	Image        sql.NullString `json:"image"`
	OrderNumber  sql.NullInt32  `json:"order_number"`
	Status       int32          `json:"status"`
	TopicCode    string         `json:"topic_code"`
}

type User struct {
	ID        string         `json:"id"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
	Status    int32          `json:"status"`
	FullName  sql.NullString `json:"full_name"`
	IsMentor  sql.NullInt32  `json:"is_mentor"`
	UserName  sql.NullString `json:"user_name"`
}
