// Code generated by sqlc. DO NOT EDIT.
// source: quick_reply.sql

package db

import (
	"context"
	"database/sql"
)

const getByScriptCode = `-- name: GetByScriptCode :many
SELECT id, script_code, content_type, title, payload, image_url, status, order_number
FROM quick_reply
WHERE script_code = $1
AND status = 1
`

func (q *Queries) GetByScriptCode(ctx context.Context, scriptCode sql.NullString) ([]QuickReply, error) {
	rows, err := q.db.QueryContext(ctx, getByScriptCode, scriptCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuickReply
	for rows.Next() {
		var i QuickReply
		if err := rows.Scan(
			&i.ID,
			&i.ScriptCode,
			&i.ContentType,
			&i.Title,
			&i.Payload,
			&i.ImageUrl,
			&i.Status,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
