// Code generated by sqlc. DO NOT EDIT.
// source: subject.sql

package db

import (
	"context"
)

const getSubjects = `-- name: GetSubjects :many
SELECT subject_code, subject_name, status, order_number, image
FROM subject
WHERE status = 1
ORDER BY order_number
`

func (q *Queries) GetSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, getSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.SubjectCode,
			&i.SubjectName,
			&i.Status,
			&i.OrderNumber,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
